### ISSUE TITLE
View and edit Vendor Supplied SBOMs

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor-ui#100]
**Target Audience**

SaaS Governance

**What’s the Value**

SaaSG users can view and **_track_** existing SBOMs in Harbor to ensure that they are being provided by Vendors in accordance with policy.

**Details**

SaaS Governance users can view and manage SBOMs within the Harbor tool.

**Definition of Done**

- Users **_must_** be able to view, sort, and filter based on SBOM the following metadata: 
  - Vendor Name
  - Application Name
  - Application Version
  - Ingestion Date(s).
- Users **_must_** be able to delete SBOMs that were uploaded in error.
- Users **_must_** see a visual indicator for SBOMs that have not been ingested within the the last 60 days.

**Out of Scope**

- Automated notifications for SBOMs that will soon be out of compliance (90 days old).
- Preventing the deletion of SBOMs.
- Soft deletes of SBOMs.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
