### ISSUE TITLE
Manage SBOM Product Associations

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor-ui#101]
**Target Audience**

The primary audience for this request is the SaaS Governance team that manually receives SBOMs. 

**What’s the Value**

Data quality done by the user instead of an engineer.

**Details**

There should be a capability to update existing SBOM / product links. The main use case for this is when the SBOM data is uploaded to the wrong vendor/product.

**Definition of Done**

A user can change the product association of an SBOM if it was uploaded to a wrong product.

**Comment by ericrippetoe** [comment]
Needs further discussion once API is active.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
