### ISSUE TITLE
View All Dependencies for SBOMs

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor-ui#102]
**Target Audience**
Harbor Team 

**What’s the Value**
Quickly validate the data is flowing through the system without having to write manual queries.

**Details**
Show a list of dependencies for an SBOM.

**Definition of Done**
Admin users will be able to view an SBOM's list of dependencies.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
