### ISSUE TITLE
View Vulnerability Data for SBOMs and Dependencies

### ISSUE THREAD

**Issue by ericrippetoe** [CMS-Enterprise/sbom-harbor-ui#103]
**Target Audience**
The primary audience for this request are:

- SaaS Governance team that manually receives SBOMs
- Harbor developers - will also need to view basic SBOM and vulnerability data.

**What’s the Value**

- Allows SaaSG team to hold vendors accountable for updating vulnerable software.
- Allows Harbor team to se a list of vulnerabilities tied to an SBOM or a specific dependency in Harbor. Is a useful form of data validation and research.

**Details**

Similar to the SDL report that gets shipped to the SDL, it would be nice to have a screen where  authenticated users can view and validate vulnerability data associated with SBOMs and their dependencies.

**Definition of Done**

A first iteration should include the following.

- Must be able to load a table view of vulnerability data stored in the Harbor database.
- Must be able to filter by:
  - SBOM
    - Component/Package name and version
    - Vendor/Product name and version
  - Vulnerability
    - Severity
    - Blast Radius
- Should be able to compare Harbor native data with SDL data.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
