### ISSUE TITLE
Design and develop CICD pipeline

### ISSUE THREAD

**Issue by talentedmrjones** [CMS-Enterprise/sbom-harbor-ui#123]
**Target Audience**

UI engineers

**What’s the Value**

This will allow automated testing, building, and deployment of UI assets to dev and prod S3 buckets

**Details**

UI react will build static components such as images, javascript, html, and css files that need to be deployed to dev and prod on merge to main

**Definition of Done**

When feature branches are merged to main, they are automatically tested, built, packaged, and deployed to dev and then production S3 buckets and viewable from `dev.harbor.cms.gov` and `harbor.cms.gov`

**Comment by sbolel** [comment]
:warning: Repository Decommission Notice: This repository is scheduled to be archived as it has been decommissioned and will no longer be actively maintained. As part of the archival process, we are closing all open issues and pull requests.
